# Generated by Django 2.0.4 on 2023-03-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Detail_pojisteni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_pojisteni_title', models.CharField(max_length=30, verbose_name='Detail_pojištění')),
            ],
            options={
                'verbose_name': 'Detail_pojištění',
                'verbose_name_plural': 'Detail_pojištění',
            },
        ),
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=200, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=180, verbose_name='Příjmení')),
                ('vek', models.CharField(default='', max_length=180, verbose_name='Věk')),
                ('adresa', models.CharField(default='', max_length=180, verbose_name='Adresa')),
                ('detail_pojisteni', models.ManyToManyField(to='databaze_pojistencu.Detail_pojisteni')),
            ],
            options={
                'verbose_name': 'Pojištěnec',
                'verbose_name_plural': 'Pojištěnci',
            },
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_pojisteni', models.CharField(max_length=80, verbose_name='Pojištění')),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='pojisteni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaze_pojistencu.Pojisteni', verbose_name='Druh pojištění'),
        ),
    ]
